language: python
python:
    - "3.6"
# command to install dependencies
install:
    - sudo apt-get install libopenmpi-dev
    - pip install codecov
    - pip install python-coveralls
    - pip install coverage==4.5.4
    - pip install -r requirements.txt
    - pip install .
# command to run tests
script:
    - nosetests --with-coverage
branches:
    only:
        - master
        - develop
after_success:
    - coveralls                     # upload reports to coveralls.io
    - codecov

