language: python

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      before_install:
        - sudo apt-get install libopenmpi-dev
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      cache:
          directories:
            - $HOME/Library/Caches/Homebrew
      before_install:
        - brew update
        - brew install open-mpi
    
# command to install dependencies
install:
    - pip install --user codecov
    - pip install --user python-coveralls
    - pip install --user coverage==4.5.4
    - pip install --user -r requirements.txt
    - pip install --user .
# command to run tests
script:
    - nosetests --with-coverage
branches:
    only:
        - master
        - develop
after_success:
    - coveralls                     # upload reports to coveralls.io
    - codecov

