language: python
python:
    - "3.6"
    
os:
    - linux
    - osx
    
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew openmpi          ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then brew install libopenmpi-dev; fi
    
# command to install dependencies
install:
    - pip install codecov
    - pip install python-coveralls
    - pip install coverage==4.5.4
    - pip install -r requirements.txt
    - pip install .
# command to run tests
script:
    - nosetests --with-coverage
branches:
    only:
        - master
        - develop
after_success:
    - coveralls                     # upload reports to coveralls.io
    - codecov

