language: python

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python:           # this works for Linux but is ignored on macOS or Windows
        - "3.8"
        - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
      before_install:
        - sudo apt-get install libopenmpi-dev
#     - name: "Python 3.7.4 on macOS"
#       os: osx
#       env: TOXENV=py33
#       osx_image: xcode7.2  # Python 3.7.4 running on macOS 10.14.4
#       language: generic       # 'language: python' is an error on Travis CI macOS
#       cache:
#           directories:
#             - $HOME/Library/Caches/Homebrew
#       before_install:
#         - brew update
#         - brew install open-mpi
#         - python3 -m venv env
#         - source env/bin/activate
    
# command to install dependencies
install:
    - pip install --upgrade pip
    - pip install codecov
    - pip install pylint
    - pip install python-coveralls
    - pip install coverage==4.5.4
    - pip install --no-use-pep517 -r requirements.txt
    - pip install .
# command to run tests
script:
    - nosetests --with-coverage
    - pylint --errors-only --disable=E1136 --generated-members=coolwarm,accumulate,multiply --ignored-modules=numpy,scipy --ignored-classes=numpy,spipy --extension-pkg-whitelist=numpy,scipy  nanonet/
branches:
    only:
        - master
        - develop
after_success:
    - coveralls                     # upload reports to coveralls.io
    - codecov

